-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Auction_tag CASCADE;
DROP TABLE IF EXISTS Tag CASCADE;
DROP TABLE IF EXISTS Comment CASCADE;
DROP TABLE IF EXISTS Bid CASCADE;
DROP TABLE IF EXISTS Auction CASCADE;
DROP TABLE IF EXISTS Person CASCADE;